##### Experiment Specific

## example
experiment_name: 'UNet_Abdomen_MR_Seg_Test'
data_root: '/opt/data/private/SFDA-DDFP/datasets/chaos'
save_root: '/opt/data/private/SFDA-DDFP/results'
source_model_path: '/opt/data/private/SFDA-DDFP/results/UNet_Abdomen_MR_Seg/T2026-03-08 20:06:24_/saved_models/best_model_epoch_139_dice_0.9294.pth'
source_sites:
- 'mr'
target_sites:
- 'ct'
dataset_name: 'abdomen'

resume: ''
continue_train: False
random_seed: 999
organ_list:
- 'Liver'
- 'R.Kidney'
- 'L.Kidney'
- 'Spleen'
# ---------
# - 'AA'
# - 'LAC'
# - 'LVC'
# - 'MYO'
# ---------
# - 'Tumor'


# Dataloader Setting
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'UNet' # DeepLab
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5

# Loss parameters
ce_ignore_index: -1
dice_ignore_index: 0

# display
save_epochs: 10
eval_epochs: 1
display_steps: 100
save_visuals: True
