##### Experiment Specific

## example
experiment_name: 'UNet_Abdomen_MR2CT_bn'
data_root: '/workspace/SFDA-DDFP/datasets/chaos'
save_root: '/workspace/SFDA-DDFP/results'
source_model_path: '/workspace/SFDA-DDFP/results/UNet_Abdomen_MR_Seg/T2026-03-08 20:06:24_/saved_models/best_model_epoch_139_dice_0.9294.pth'
source_sites:
- 'mr'
target_sites:
- 'ct'
dataset_name: 'abdomen'

resume_dir: ''
continue_train: False
total_epochs: 1

random_seed: 999
organ_list:
- 'Liver'
- 'R.Kidney'
- 'L.Kidney'
- 'Spleen'

# Dataloader Setting
patient_level_dataloader: False
img_size:
- 256
- 256
# batch_size: 16
batch_size: 32
num_workers: 8

# Model 
arch: 'UNet'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5
num_prototypes: 1

# Optim parameters
lr: 0.0001

dice_ignore_index: -1
# display
save_steps: 50
eval_steps: 1
display_steps: 100
save_visuals: True
