##### Experiment Specific
doing: 'train'

## example
experiment_name: 'UNet_Abdomen_MR2CT_pmt'
data_root: '/workspace/SFDA-DDFP/datasets/chaos'
save_root: '/workspace/SFDA-DDFP/results'
source_model_path:  '/workspace/SFDA-DDFP/results/UNet_Abdomen_MR_Seg/T2026-03-08 20:06:24_/saved_models/best_model_epoch_139_dice_0.9294.pth'
bn_align_model:  '/workspace/SFDA-DDFP/results/UNet_Abdomen_MR2CT_bn/T2026-03-27 10:16:22_tuneall_epoch10/saved_models/model_step_0_dice_0.6305.pth'
target_sites:
- 'ct'
dataset_name: 'abdomen'
w1: 1
w2: 1
w3: 10
lr: 0.0005
wcls: 
- 40 
- 40
- 40
- 40
- 40
wglo: 0.4
alpha: 0.8
theta: 0.2


# experiment_name: 'UNet_Abdomen_MR2CT_pmt'
# data_root: '/mnt/ExtData/Data/processed/chaos/'
# save_root: '/mnt/ExtData/SFDA_DDFP/log/revise/'
# source_model_path: 
# bn_align_model: 
# target_sites:
# - 'ct'
# dataset_name: 'abdomen'
# w1: 0.1
# w2: 1
# w3: 10
# lr: 0.0005
# wcls: 
# - 40 
# - 40
# - 40
# - 40
# - 40
# wglo: 0.4
# alpha: 0.8
# theta: 0.2


# experiment_name: 'UNet_cardiac_CT2MR_pmt'
# data_root: '/mnt/ExtData/Data/MMWHS'
# save_root: '/mnt/ExtData/SFDA_DDFP/log/revise/'
# source_model_path:
# bn_align_model: 
# target_sites:
# - 'mr'
# dataset_name: 'cardiac'
# w1: 4
# w2: 0.1
# w3: 10
# lr: 0.001
# wcls: 
# - 40 
# - 40
# - 40
# - 40
# - 40
# wglo: 0.4
# alpha: 0.8
# theta: 0.2


# experiment_name: 'UNet_cardiac_MR2CT_pmt'
# data_root: '/mnt/ExtData/Data/MMWHS'
# save_root: '/mnt/ExtData/SFDA_DDFP/log/revise/'
# source_model_path: 
# bn_align_model:
# target_sites:
# - 'ct'
# dataset_name: 'cardiac'
# w1: 1
# w2: 1
# w3: 10
# lr: 0.001
# wcls: 
# - 40 
# - 40
# - 40
# - 40
# - 40
# wglo: 0.4
# alpha: 0.8
# theta: 0.2


# experiment_name: 'UNet_Brats_flair_Seg'
# data_root: '/mnt/ExtData/Data/preprocess_brats2018/'
# save_root: '/mnt/ExtData/SFDA_DDFP/log/brats18'
# source_model_path: 
# bn_align_model: 
# source_sites:
# - 'flair'
# target_sites:
# - 't2'
# dataset_name: 'brats'
# w1: 5
# w2: 10
# w3: 20
# lr: 0.0005
# wcls: 
# - 40 
# - 40
# - 40
# - 40
# - 40
# wglo: 0.4
# alpha: 0.8
# theta: 0.2


# experiment_name: 'UNet_Brats_t22flair_Seg'
# data_root: '/mnt/ExtData/Data/preprocess_brats2018/'
# save_root: '/mnt/ExtData/SFDA_DDFP/log/brats18'
# bn_align_model: 
# source_model_path: 
# source_sites:
# - 't2'
# target_sites:
# - 'flair'
# dataset_name: 'brats'
# w1: 5
# w2: 1
# w3: 10
# lr: 0.0005
# wcls: 
# - 40 
# - 40
# - 40
# - 40
# - 40
# wglo: 0.4
# alpha: 0.8
# theta: 0.2


pmt_type: 'Data' #, 'Data' #'Domain' 'Spatial', None
train_type: 'LSET1' #pmt | LSET1 | pmtinc | All | besideLSET1 | LSET1wodown3 | LSET1wodown23
pmt_size: 256
es_step: 10 #5
resume_dir: ''
continue_train: False
total_epochs: 1

random_seed: 999
organ_list:
- 'Liver'
- 'R.Kidney'
- 'L.Kidney'
- 'Spleen'
# ---------
# - 'AA'
# - 'LAC'
# - 'LVC'
# - 'MYO'
# ---------
# - 'Tumor'

# Dataloader Setting
patient_level_dataloader: False
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'Pmt_UNet' # Pmt_DeepLab | UNet
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5
num_prototypes: 1

# Loss parameters
nav_t: 1
beta: 0.001
s_par: 0.5
dice_ignore_index: -1
# display
save_steps: 50
eval_steps: 2
display_steps: 20
save_visuals: True

# test
test: False
